let citas = [
    {'autor': 'Albert Einstein', 'texto': 'No poseo talentos especiales. Solo soy apasionadamente curioso.'},
    {'autor': 'Anónimo', 'texto': 'Semanas de programación te pueden ahorrar horas de planeación.'},
    {'autor': 'Alan Kay', 'texto': 'La mejor forma de predecir el futuro es inventarlo.'},
    {'autor': 'Amelia Earhart', 'texto': 'Lo más dificil es tomar la decisión de actuar. El resto es simplemente tenacidad.'},
    {'autor': 'Aristotle', 'texto': 'La calidad no es un acto, es un hábito.'},
    {'autor': 'Benjamin Franklin', 'texto': 'Dímelo y lo olvidaré. Enséñamelo y lo recordaré. Involúcrame y lo aprenderé.'},
    {'autor': 'Charles R. Swindoll', 'texto': 'La vida es 10% lo que te ocurre y 90% cómo reaccionas.'},
    {'autor': 'Jane Goodall', 'texto': 'Lo que haces hace una diferencia. Y debes decidir si qué tipo de diferencia quieres hacer.'},
    {'autor': 'John Muir', 'texto': 'El poder de la imaginación nos hace infinitos.'},
    {'autor': 'Mark Twain', 'texto': 'Los dos días más importantes de tu vida son el día que naciste y el día que descubres por qué.'},
    {'autor': 'Mahatma Gandhi', 'texto': 'Sé el cambio que quieres ver en el mundo'},
    {'autor': 'Vince Lombardi', 'texto': 'No se trata de si van a derribarte, se trata de si vas a levantarte cuando lo hagan'},
    {'autor': 'Eleanor Roosevelt', 'texto': 'Nadie puede hacerte sentir inferior sin tu consentimiento'},
    {'autor': 'Ana Frank', 'texto': 'Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo'},
    {'autor': 'Winston Churchill', 'texto': 'El pesimista ve dificultades en cada oportunidad. El optimista ve oportunidades en cada dificultad'},
    {'autor': 'Leon Tolstoi', 'texto': 'Muchos piensan en cambiar el mundo, pero casi nadie piensa en cambiarse a sí mismo'},
    {'autor': 'Steve Jobs', 'texto': 'Si estás trabajando en algo que te importa de verdad, nadie tiene que empujarte: tu visión te empuja'},
    {'autor': 'Zig Ziglar', 'texto': 'No tienes que ser grande para empezar. Pero tienes que empezar para poder ser grande'},
    {'autor': 'Maya Angelou', 'texto': 'Podemos sufrir muchas derrotas pero no debemos ser derrotados'},
    {'autor': 'Anónimo', 'texto': 'El momento en que quieres dejarlo es justo el momento en que tienes que seguir avanzando'},
    {'autor': 'Napoleon Hill', 'texto': 'No esperes. Nunca va a ser el momento adecuado'},
    {'autor': 'Albert Einstein', 'texto': 'La creatividad es la inteligencia divirtiéndose'},
    {'autor': 'Roy T. Bennet', 'texto': 'Rodéate de personas que crean en tus sueños, animen tus ideas, apoyen tus ambiciones, y saquen lo mejor de ti'},
    {'autor': 'Robin Williams', 'texto': 'No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo'},
    {'autor': 'C.S. Lewis', 'texto': 'Nunca eres demasiado viejo para marcarte otra meta o tener un nuevo sueño'},
    {'autor': 'Franz Kafka', 'texto': 'No te pliegues. No lo diluyas. No intentes hacerlo lógico. No adaptes tu propia alma a las costumbres de los demás. En lugar de todo eso, sigue tu propia obsesión implacablemente'},
    {'autor': 'Louis D. Brandeis', 'texto': 'La mayor parte de las grandes cosas que ha conseguido el hombre, fueron declaradas imposibles antes de que alguien las hiciera'},
    {'autor': 'Sheryl Sandberg', 'texto': 'La verdadera motivación procede de trabajar en cosas que nos importan'},
    {'autor': 'Benjamin Franklin', 'texto': 'La energía y la persistencia conquistan todas las cosas'},
    {'autor': 'Platón', 'texto': 'Sé amable, porque toda persona que conoces está librando una gran batalla'},
    {'autor': 'Albert Einstein', 'texto': 'La lógica te llevará de la A a la Z. La imaginación te llevará a cualquier lugar'},
    {'autor': 'Santiago Ramón y Cajal', 'texto': 'Las ideas no duran mucho. Hay que hacer algo con ellas'},
    {'autor': 'Jonathan Swift', 'texto': 'Te deseo que estés vivo cada día de tu vida'},
    {'autor': 'Aristóteles', 'texto': 'La excelencia no es un acto, es un hábito'},
    {'autor': 'Oscar Wilde', 'texto': 'Sé tú mismo. Todos los demás ya están ocupados'},
    {'autor': 'Muhammad Ali', 'texto': 'No cuentes los días. Haz que los días cuenten'},
    {'autor': 'Will Rogers', 'texto': 'No dejes que tu pasado ocupe todo tu presente'},
    {'autor': 'Epicteto', 'texto': 'Lo que importa no es lo que te ocurre, sino cómo reaccionas a ello'},
    {'autor': 'Dr. Seuss', 'texto': 'A veces no conoces el valor de un momento hasta que se ha convertido en un recuerdo'},
    {'autor': 'Marco Aurelio', 'texto': 'No es la muerte lo que debes temer, sino nunca empezar a vivir'},
    {'autor': 'Francisco de Quevedo', 'texto': 'El que pasa el tiempo arrepintiéndose del pasado, pierde el presente y arriesga el futuro'},
    {'autor': 'Albert Einstein', 'texto': 'La vida es como montar en bicicleta. Para mantener el equilibrio tienes que avanzar'},
    {'autor': 'Charles R. Swindoll', 'texto': 'La vida es en un 10% lo que te ocurre, y en un 90% cómo te lo tomas'},
    {'autor': 'Walt Whitman', 'texto': 'Camina hacia el sol y las sombras quedarán siempre tras de ti'},
    {'autor': 'Marilyn Monroe', 'texto': 'No pares cuando estés cansado. Para cuando hayas terminado'},
    {'autor': 'Miguel de Cervantes', 'texto': 'Qué locura o desatino me lleva a contar las faltas ajenas, teniendo tanto que decir de las mías'},
    {'autor': 'Mahatma Gandhi', 'texto': 'Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre'},
    {'autor': 'Carol Burnett', 'texto': 'Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí'},
    {'autor': 'San Francisco de Asís', 'texto': 'Hemos sido llamados para curar heridas, para unir lo que se ha separado, y para traer a casa a quienes han perdido su camino'},
    {'autor': 'Michelangelo Buonarroti', 'texto': 'El mayor peligro para la mayoría de nosotros no es apuntar demasiado alto y fallar, sino apuntar demasiado bajo y acertar'},
    {'autor': 'Epicteto', 'texto': 'El que cree que lo sabe todo es incapaz de aprender'},
    {'autor': 'Michael Altshuler', 'texto': 'La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto'},
    {'autor': 'Maya Angelou', 'texto': 'Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud'},
    {'autor': 'Gabriel García Márquez', 'texto': 'No es verdad que las personas paren de perseguir sueños porque se hacen viejos. Se hacen viejos porque dejar de perseguir sueños'},
    {'autor': 'Jim Rohn', 'texto': 'La felicidad no ocurre por casualidad, sino por elección'},
    {'autor': 'William Barclay', 'texto': 'Hay dos grandes días en la vida de una persona –el día en que nacemos, y el día en que descubrimos para qué'},
    {'autor': 'Henry Ford', 'texto': 'Tanto si crees que puedes como si crees que no puedes, tienes razón'},
    {'autor': 'Les Brown', 'texto': 'Demasiada gente no vive sus sueños porque está ocupada viviendo sus miedos'},
    {'autor': 'Robert F. Kennedy', 'texto': 'Solo aquellos que se arriesgan a caer pueden conseguir grandes cosas'},
    {'autor': 'Dr. Henry Link', 'texto': 'Generamos miedos cuando estamos sentados. Y los superamos con la acción'},
    {'autor': 'Emilio Valcárcel', 'texto': 'No mires hacia atrás –no es allí adonde vas'},
    {'autor': 'Thoreau', 'texto': 'Avanza con confianza en la dirección de tus sueños'},
    {'autor': 'Confucio', 'texto': 'Saber qué es lo correcto y no hacerlo es falta de valor'},
    {'autor': 'George Addair', 'texto': 'Todo lo que siempre deseaste está al otro lado del miedo'},
    {'autor': 'Dale Carnegie', 'texto': 'La inacción produce duda y miedo. La acción genera confianza y valor. Si quieres dominar el miedo no te quedes en casa pensando sobre ello: sal fuera y enfréntate a él'},
    {'autor': 'Eleanor Roosevelt', 'texto': 'Tienes que hacer las cosas que crees que no puedes hacer'},
    {'autor': 'Anais Nin', 'texto': 'Tu vida se encoge o se expande en proporción a tu valor'},
    {'autor': 'Brian Tracy', 'texto': 'Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo cuando intentas algo nuevo'},
    {'autor': 'Nelson Mandela', 'texto': 'He aprendido que el valor no es la ausencia de miedo, sino el triunfo sobre él. El hombre valiente no es el que no siente miedo, sino el que lo domina'},
    {'autor': 'J.K. Rowling', 'texto': 'Es imposible vivir sin fracasar en algo, a no ser que vivas con tanto cuidado que dé igual si has vivido o no –en cuyo caso, ya has fracasado'},
    {'autor': 'Hellen Keller', 'texto': 'El carácter no puede desarrollarse en la calma y en la facilidad. Solo a través de la experiencia y del sufrimiento se fortalece el alma, se inspira la ambición, y se alcanza el éxito'},
    {'autor': 'Ella Fitzgerald', 'texto': 'Lo que cuenta no es de dónde vienes, sino adónde vas'},
    {'autor': 'Mae West', 'texto': 'Sólo se vive una vez. Pero si lo haces bien, una vez basta'},
    {'autor': 'Winston Churchill', 'texto': 'Nunca, nunca, nunca abandones'},
    {'autor': 'Mahatma Gandhi', 'texto': 'La fuerza no procede de la capacidad física, sino de una voluntad indomable'},
    {'autor': 'Benjamin Franklin', 'texto': 'La diligencia es la madre de la buena suerte'},
    {'autor': 'Marco Aurelio', 'texto': 'Cuando te levantes por la mañana piensa en qué privilegio es estar vivo, pensar, disfrutar, amar'},
    {'autor': 'Santiago Ramón y Cajal', 'texto': 'Si hay algo en nosotros verdaderamente divino, es la voluntad. Por ella afirmamos la personalidad, templamos el carácter, desafiamos la adversidad, reconstruimos el cerebro y nos superamos diariamente'},
    {'autor': 'Miguel de Unamuno', 'texto': 'Solo el que intenta lo absurdo es capaz de conseguir lo que parecía imposible'},
    {'autor': 'Alexander Graham Bell', 'texto': 'Concentra todos tus pensamientos en el trabajo que tienes entre manos. Los rayos del sol no encienden fuego hasta que los enfocas en un solo punto'},
    {'autor': 'Epicuro', 'texto': 'Cuanto más grande es la dificultad, más gloria hay en superarla'},
    {'autor': 'Martin Luther King', 'texto': 'Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, arrástrate, pero hagas lo que hagas sigue moviéndote hacia adelante'},
    {'autor': 'Peter Diamandis', 'texto': 'La palabra ‘no’ solo significa que empieces otra vez en un nivel superior'},
    {'autor': 'Anónimo', 'texto': 'No he llegado tan lejos solo para llegar hasta aquí'},
    {'autor': 'Anónimo', 'texto': 'Si no puedes dejar de pensar en ello, no dejes de trabajar en ello'},
    {'autor': 'Aristóteles', 'texto': 'Somos lo que hacemos de forma repetida. La excelencia no es un acto, sino un hábito'},
    {'autor': 'George Bernard Shaw', 'texto': 'En la vida no se trata de encontrarte a ti mismo. Se trata de inventarte a ti mismo'},
    {'autor': 'Steve Jobs', 'texto': 'Tu tiempo es limitado, no lo malgastes viviendo la vida de otro. No te dejes atrapar por el dogma'},
    {'autor': 'Emilio Valcárcel', 'texto': 'No preguntes cuál es tu lugar en el mundo: siéntate en él'},
    {'autor': 'Ralph Waldo Emerson', 'texto': 'El mayor logro es ser tú mismo en un mundo que continuamente trata de convertirte en otra cosa'},
    {'autor': 'Estée Lauder', 'texto': 'Nunca soñé con el éxito. Trabajé por él'},
    {'autor': 'George Eliot', 'texto': 'Nunca es demasiado tarde para ser lo que podrías haber sido'},
    {'autor': 'Eminem', 'texto': 'El éxito es mi única opción, no el fracaso'},
    {'autor': 'Connor McGregor', 'texto': 'No es que tenga talento: estoy obsesionado'},
    {'autor': 'Marco Aurelio', 'texto': 'No tienes poder sobre los acontecimientos exteriores –pero sí sobre tu mente. Aprende esto, y encontrarás tu fuerza'},
    {'autor': 'Concepción Arenal', 'texto': 'El hombre que se levanta es más grande que el que nunca ha caído'},
    {'autor': 'Sócrates', 'texto': 'La mejor almohada para dormir es una conciencia tranquila'},
    {'autor': 'Simón Bolívar', 'texto': 'El arte de vencer se aprende en las derrotas'},
    {'autor': 'Oscar Wilde', 'texto': 'Olvida siempre a tus enemigos: nada les molesta más'},
    {'autor': 'Francis Bacon', 'texto': 'El conocimiento es poder'},
    {'autor': 'Emilio Valcárcel', 'texto': 'La buena vida es una forma de pensar'},
    {'autor': 'José Ortega y Gasset', 'texto': 'Solo quien se maneja a sí mismo puede manejar a los demás'},
    {'autor': 'Anónimo', 'texto': 'Ser positivo no significa que todo vaya a salir bien. Significa saber que vas a estar bien independientemente de cómo salgan las cosas'},
    {'autor': 'Enrique Jardiel Poncela', 'texto': 'Todos los hombres que no tienen nada importante que decir hablan a gritos'},
    {'autor': 'Epicteto', 'texto': 'Tenemos dos orejas y una boca para escuchar el doble de lo que hablamos'},
    {'autor': 'Serena Williams', 'texto': 'Un campeón se distingue no por sus victorias, sino por cómo se recupera de sus derrotas'},
    {'autor': 'Buda', 'texto': 'Aferrarse al rencor es como beber veneno y esperar que otra persona muera'},
    {'autor': 'Albert Einstein', 'texto': 'Una persona inteligente resuelve los problemas. Una persona sabia los evita'},
    {'autor': 'C.S. Lewis', 'texto': 'A menudo las dificultades preparan a una persona normal para un destino extraordinario'},
    {'autor': 'Mark Twain', 'texto': 'Dentro de veinte años estarás más arrepentido por las cosas que no hiciste que por aquellas que hiciste'},
    {'autor': 'Thomas Carlyle', 'texto': 'La perserverancia a pesar de todos los obstáculos, desánimos e imposibilidades: esto es lo que distingue el alma fuerte de la débil'},
    {'autor': 'Simon Sinek', 'texto': 'Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que te importa de verdad se llama pasión'},
    {'autor': 'Dalai Lama', 'texto': 'Recuerda que, a veces, no conseguir lo que quieres es un gran golpe de suerte'},
    {'autor': 'Walter Scott', 'texto': 'Para tener éxito la actitud es tan importante como la habilidad'},
    {'autor': 'Sheryl Sandberg', 'texto': 'Hecho es mejor que perfecto'},
    {'autor': 'Helen Keller', 'texto': 'En ese lugar entre tu zona de confort y tu sueño es donde está la verdadera vida'},
    {'autor': 'San Francisco de Asís', 'texto': 'Empieza haciendo lo que es necesario; después haz lo que es posible; y pronto te encontrarás haciendo lo imposible'},
    {'autor': 'Anónimo', 'texto': 'Las frases motivadoras pueden inspirarte; pero es la acción la que te completa'},
    {'autor': 'Henry Ford', 'texto': 'Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta'},
    {'autor': 'Stephen R. Covey', 'texto': 'Más que producto de mis circunstancias, soy producto de mis decisiones'},
    {'autor': 'Ayn Rand', 'texto': 'La cuestión no es quién va a permitírmelo, sino quién va a ser capaz de pararme'},
    {'autor': 'Napoleon Hill', 'texto': 'La acción es la verdadera medida de la inteligencia'},
    {'autor': 'Vince Lombardi', 'texto': 'La perfección es imposible. Pero si aspiramos a ella podemos alcanzar la excelencia'},
    {'autor': 'Steve Martin', 'texto': 'Sé tan bueno que no puedan ignorarte'},
    {'autor': 'Virgilio', 'texto': 'La Fortuna ayuda a los audaces'}
  ];